In [1]:
import sys
print(sys.version)

3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)]


In [2]:
import numpy as np
import pandas as pd
print(np.__version__)
print(pd.__version__)

2.4.2
3.0.1


In [3]:
# Create a 2D array by passing a list of lists to np.array() function.
arr_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr_2d.shape)
print(arr_2d.ndim)
arr_2d

(4, 2)
2


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
# Create a 3D array by passing a list of two lists of lists to np.array() function.
arr_3d = np.array([[[1, 2, 3],
                   [3, 4, 5]],

                  [[5, 6, 7],
                   [7, 8, 9]]]
)

print(arr_3d.shape)
print(arr_3d.ndim)
arr_3d

(2, 2, 3)
3


array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [5]:
# Create new array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
# The mean() method returns the mean of the elements in an array.
np.mean(arr)

[1 2 3 4 5]


np.float64(3.0)

In [6]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [8]:
np.full((5, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [9]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [13]:
array_2d = np.array([(1, 2, 3), (4, 5,0)])
array_2d.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 0]])

In [14]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
array_2d.tolist()

[[1, 2, 3], [4, 5, 6]]

In [ ]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a.max())
print(a.mean())
print(a.min())
print(a.std())

6
3.5
1
1.707825127659933


In [17]:
import numpy as np

a = np.array([(1, 2, 3), (4, 5, 6)])

# Find the max of the entire array (Default)
print(a.max())         # Output: 6

# Find the max going DOWN the columns
print(a.max(axis=0))   # Output: [4 5 6]

# Find the max going ACROSS the rows
print(a.max(axis=1))   # Output: [3 6]

6
[4 5 6]
[3 6]


In [18]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)


(2, 3)
int64
6
[[1 4]
 [2 5]
 [3 6]]


In [19]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a[1])
print(a[0, 1])
print(a[1, 2])

[4 5 6]
2
6


In [20]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
a[:, 1:]

[[1 2 3]
 [4 5 6]]


array([[2, 3],
       [5, 6]])

In [21]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([[1, 2, 3], [1, 2, 3]])
print(a + b)
print(a * b)

[[2 4 6]
 [5 7 9]]
[[ 1  4  9]
 [ 4 10 18]]


In [22]:
a = np.array([(1, 2), (3, 4)])
a[1][1] = 100
a


array([[  1,   2],
       [  3, 100]])

In [23]:
a = np.array([1, 2, 3])
a[3] = 100
a


IndexError: index 3 is out of bounds for axis 0 with size 3